"""Add spendType column

Revision ID: 1a540dbd8f90
Revises: 
Create Date: 2025-07-24 02:57:29.115164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a540dbd8f90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('emotion_category')
    op.drop_table('admin_weekly_report')
    op.drop_table('record')
    op.drop_index(op.f('unique_user_report'), table_name='user_report')
    op.drop_table('user_report')
    op.drop_table('spend_category')
    op.drop_index(op.f('uniq_user_month'), table_name='total_budget')
    op.drop_table('total_budget')
    op.drop_table('admin_daily_report')
    op.drop_index(op.f('uniq_total_category'), table_name='category_budget')
    op.drop_table('category_budget')
    op.drop_table('admin_monthly_report')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_monthly_report',
    sa.Column('userId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emotionCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalSpend', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emotionCategoryId'], ['emotion_category.emotionCategoryId'], name=op.f('admin_monthly_report_ibfk_2')),
    sa.ForeignKeyConstraint(['spendCategoryId'], ['spend_category.spendCategoryId'], name=op.f('admin_monthly_report_ibfk_3')),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], name=op.f('admin_monthly_report_ibfk_1')),
    sa.PrimaryKeyConstraint('userId', 'year', 'month', 'emotionCategoryId', 'spendCategoryId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category_budget',
    sa.Column('categoryBudgetId', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('totalBudgetId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spendCategoryId'], ['spend_category.spendCategoryId'], name=op.f('fk_categorybudget_category')),
    sa.ForeignKeyConstraint(['totalBudgetId'], ['total_budget.totalBudgetId'], name=op.f('fk_categorybudget_total'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('categoryBudgetId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uniq_total_category'), 'category_budget', ['totalBudgetId', 'spendCategoryId'], unique=True)
    op.create_table('admin_daily_report',
    sa.Column('userId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('recordDate', sa.DATE(), nullable=False),
    sa.Column('emotionCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalSpend', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emotionCategoryId'], ['emotion_category.emotionCategoryId'], name=op.f('admin_daily_report_ibfk_2')),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], name=op.f('admin_daily_report_ibfk_1')),
    sa.PrimaryKeyConstraint('userId', 'recordDate', 'emotionCategoryId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('total_budget',
    sa.Column('userId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('totalBudgetId', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('budgetMonth', sa.DATE(), nullable=False),
    sa.Column('totalAmount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], name=op.f('fk_totalbudget_user')),
    sa.PrimaryKeyConstraint('totalBudgetId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uniq_user_month'), 'total_budget', ['userId', 'budgetMonth'], unique=True)
    op.create_table('spend_category',
    sa.Column('spendCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCategoryName', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('spendCategoryId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_report',
    sa.Column('reportId', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reportDate', sa.DATE(), nullable=False),
    sa.Column('reportType', mysql.ENUM('daily', 'weekly', 'monthly'), nullable=False),
    sa.Column('reportText', mysql.TEXT(), nullable=False),
    sa.Column('spendType', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], name=op.f('user_report_ibfk_1')),
    sa.PrimaryKeyConstraint('reportId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('unique_user_report'), 'user_report', ['userId', 'reportDate', 'reportType'], unique=True)
    op.create_table('record',
    sa.Column('spendId', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('emotionCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendItem', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('spendCost', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendDate', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['emotionCategoryId'], ['emotion_category.emotionCategoryId'], name=op.f('fk_record_emotion_category')),
    sa.ForeignKeyConstraint(['spendCategoryId'], ['spend_category.spendCategoryId'], name=op.f('fk_record_spend_category')),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], name=op.f('fk_record_member')),
    sa.PrimaryKeyConstraint('spendId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin_weekly_report',
    sa.Column('userId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emotionCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('spendCount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalSpend', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emotionCategoryId'], ['emotion_category.emotionCategoryId'], name=op.f('admin_weekly_report_ibfk_2')),
    sa.ForeignKeyConstraint(['spendCategoryId'], ['spend_category.spendCategoryId'], name=op.f('admin_weekly_report_ibfk_3')),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], name=op.f('admin_weekly_report_ibfk_1')),
    sa.PrimaryKeyConstraint('userId', 'year', 'week', 'emotionCategoryId', 'spendCategoryId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('emotion_category',
    sa.Column('emotionCategoryId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('emotionCategoryName', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('emotionCategoryId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('userId', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
