"""fix: remove duplicate index

Revision ID: ae333a6a8b89
Revises: 1a540dbd8f90
Create Date: 2025-07-29 19:37:13.330643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae333a6a8b89'
down_revision: Union[str, Sequence[str], None] = '1a540dbd8f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge')
    op.drop_table('challenge_participant')
    op.add_column('admin_monthly_report', sa.Column('recordDate', sa.DateTime(), nullable=False))
    op.drop_column('admin_monthly_report', 'year')
    op.drop_column('admin_monthly_report', 'month')
    op.add_column('admin_weekly_report', sa.Column('recordDate', sa.DateTime(), nullable=False))
    op.drop_column('admin_weekly_report', 'year')
    op.drop_column('admin_weekly_report', 'week')
    op.alter_column('category_budget', 'amount',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_report', 'spendType',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_report', 'spendType',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('category_budget', 'amount',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('admin_weekly_report', sa.Column('week', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('admin_weekly_report', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('admin_weekly_report', 'recordDate')
    op.add_column('admin_monthly_report', sa.Column('month', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('admin_monthly_report', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('admin_monthly_report', 'recordDate')
    op.create_table('challenge_participant',
    sa.Column('challengeId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('userId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('isHost', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challengeId'], ['challenge.challengeId'], name=op.f('challenge_participant_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], name=op.f('challenge_participant_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challengeId', 'userId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('challenge',
    sa.Column('challengeId', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('publicityType', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('challengeType', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('goalCount', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('challengeId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
